// const text1="scientific innovations or technology is the most amazing thing that has ever happened to humankind in this modern world technology is no more a luxury it has become a necessity life without technology is next to impossible since humans have become dependent on technological advancements for every human activity we need a machine and then there comes technology it has made all our lives easier and more convenient and has also made transportation education labour etc more accessible technological breakthroughs change from time to time in today's fast-paced ever-changing world however in today's world technology plays a critical role in strengthening a country's economy and people's lives"
// const text2="we are all surrounded by technology from all corners from waking up in the morning till we sleep in some way or the other we need technology technology our new present and future is making human lives easier and more convenient with new technological innovations human beings have become more dependent on science and technology we rely on technology for all our activities and have become an integral part of our lives the entire civilization has become reliant on the modern technology it employs life and business would come to a halt without technology it is beneficial to society but it must be handled cautiously it is helpful and at the same time it is harmful it has reduced man's labour and improved the productivity of the work but it has also reduced employment at the same time so technology should be used only to a certain extent by not depending on it completely"
// const text3="science and technology have become essential aspects of our lives technology was a luxury at a point in time but now it has become a necessity it is impossible to survive without electricity television music systems mobile phones internet connections etc we start and end our day with technology so it is indeed difficult to imagine our life without technology but it should be used with caution if we become too dependent on technology it will end up being harmful to us and our health Overuse of technology can also become self-destructive so it is important everyone uses technology only when necessary advanced technology has increased productivity across all fields of work technology is our new present and future and it has made life easier and more convenient for us humans have become more reliant on science and technology as a result of technological advancements every human activity has now been replaced by one created by machines we rely on technology for every aspect of our lives and it has become an inseparable element of our lives the use of contemporary technology has made the entire civilization reliant on it without technology life and business would grind to a halt"
// const text4="from the moment we open our eyes we are surrounded by technology the fans lights televisions computers induction stoves etc it is just not possible to move a step further without using technology there was a time when people used to wait for months to receive a letter from their close ones but now we all are just a click away if you are missing someone you just have to click once for a video call or text message the cost has also reduced with time if you crave a piece of cake then the microwave is the solution if you are tired and unable to wash utensils then a dishwasher is the solution if you want to party then the music system is the solution technology is the ultimate solution to every problem that a human being is facing and scientists are so alert about the same that they come up with new and innovative solutions to every problem it is however important that you do not completely rely on technology technology has become a vital part of our daily lives since we rely on it for all of our activities the use of contemporary technology has made the entire civilization dependent without technology life and commerce would grind to a halt technology has a positive impact on society but it must be managed with caution it is both beneficial and detrimental"
// function infotext(text){
//     let words = text.split(' ');
//     let nw = words.length;
//     let nl = text.length;
//     return[nw,nl];
// }

